databases:
  - name: cinemaReviews_DB
    databaseName: cinemareviews_db
    user: cinemaReviews_DB
    region: singapore
services:
  - type: web
    name: cinemaReviews_DB
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinemaReviews_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false







